# Generated by Django 3.1 on 2022-08-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220802_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_lastname',
            new_name='last_name',
        ),
    ]
